// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamemsg.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

////////////////////////////////////////////////////////////////
// 心跳 1
type GameReqHeartBeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameReqHeartBeat) Reset()         { *m = GameReqHeartBeat{} }
func (m *GameReqHeartBeat) String() string { return proto.CompactTextString(m) }
func (*GameReqHeartBeat) ProtoMessage()    {}
func (*GameReqHeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ecd7041722872b9, []int{0}
}

func (m *GameReqHeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameReqHeartBeat.Unmarshal(m, b)
}
func (m *GameReqHeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameReqHeartBeat.Marshal(b, m, deterministic)
}
func (m *GameReqHeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameReqHeartBeat.Merge(m, src)
}
func (m *GameReqHeartBeat) XXX_Size() int {
	return xxx_messageInfo_GameReqHeartBeat.Size(m)
}
func (m *GameReqHeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_GameReqHeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_GameReqHeartBeat proto.InternalMessageInfo

// 心跳 2
type GameResHeartBeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResHeartBeat) Reset()         { *m = GameResHeartBeat{} }
func (m *GameResHeartBeat) String() string { return proto.CompactTextString(m) }
func (*GameResHeartBeat) ProtoMessage()    {}
func (*GameResHeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ecd7041722872b9, []int{1}
}

func (m *GameResHeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResHeartBeat.Unmarshal(m, b)
}
func (m *GameResHeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResHeartBeat.Marshal(b, m, deterministic)
}
func (m *GameResHeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResHeartBeat.Merge(m, src)
}
func (m *GameResHeartBeat) XXX_Size() int {
	return xxx_messageInfo_GameResHeartBeat.Size(m)
}
func (m *GameResHeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResHeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_GameResHeartBeat proto.InternalMessageInfo

// 同步时间 1
type GameReqSyncTime struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameReqSyncTime) Reset()         { *m = GameReqSyncTime{} }
func (m *GameReqSyncTime) String() string { return proto.CompactTextString(m) }
func (*GameReqSyncTime) ProtoMessage()    {}
func (*GameReqSyncTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ecd7041722872b9, []int{2}
}

func (m *GameReqSyncTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameReqSyncTime.Unmarshal(m, b)
}
func (m *GameReqSyncTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameReqSyncTime.Marshal(b, m, deterministic)
}
func (m *GameReqSyncTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameReqSyncTime.Merge(m, src)
}
func (m *GameReqSyncTime) XXX_Size() int {
	return xxx_messageInfo_GameReqSyncTime.Size(m)
}
func (m *GameReqSyncTime) XXX_DiscardUnknown() {
	xxx_messageInfo_GameReqSyncTime.DiscardUnknown(m)
}

var xxx_messageInfo_GameReqSyncTime proto.InternalMessageInfo

// 同步时间 2
type GameResSyncTime struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Minute               int32    `protobuf:"varint,4,opt,name=minute,proto3" json:"minute,omitempty"`
	Time                 uint64   `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResSyncTime) Reset()         { *m = GameResSyncTime{} }
func (m *GameResSyncTime) String() string { return proto.CompactTextString(m) }
func (*GameResSyncTime) ProtoMessage()    {}
func (*GameResSyncTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ecd7041722872b9, []int{3}
}

func (m *GameResSyncTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResSyncTime.Unmarshal(m, b)
}
func (m *GameResSyncTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResSyncTime.Marshal(b, m, deterministic)
}
func (m *GameResSyncTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResSyncTime.Merge(m, src)
}
func (m *GameResSyncTime) XXX_Size() int {
	return xxx_messageInfo_GameResSyncTime.Size(m)
}
func (m *GameResSyncTime) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResSyncTime.DiscardUnknown(m)
}

var xxx_messageInfo_GameResSyncTime proto.InternalMessageInfo

func (m *GameResSyncTime) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *GameResSyncTime) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *GameResSyncTime) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *GameResSyncTime) GetMinute() int32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *GameResSyncTime) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// 登录验证 1
type GameReqLogin struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameReqLogin) Reset()         { *m = GameReqLogin{} }
func (m *GameReqLogin) String() string { return proto.CompactTextString(m) }
func (*GameReqLogin) ProtoMessage()    {}
func (*GameReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ecd7041722872b9, []int{4}
}

func (m *GameReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameReqLogin.Unmarshal(m, b)
}
func (m *GameReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameReqLogin.Marshal(b, m, deterministic)
}
func (m *GameReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameReqLogin.Merge(m, src)
}
func (m *GameReqLogin) XXX_Size() int {
	return xxx_messageInfo_GameReqLogin.Size(m)
}
func (m *GameReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_GameReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_GameReqLogin proto.InternalMessageInfo

// 登录验证 2
type GameResLogin struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResLogin) Reset()         { *m = GameResLogin{} }
func (m *GameResLogin) String() string { return proto.CompactTextString(m) }
func (*GameResLogin) ProtoMessage()    {}
func (*GameResLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ecd7041722872b9, []int{5}
}

func (m *GameResLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResLogin.Unmarshal(m, b)
}
func (m *GameResLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResLogin.Marshal(b, m, deterministic)
}
func (m *GameResLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResLogin.Merge(m, src)
}
func (m *GameResLogin) XXX_Size() int {
	return xxx_messageInfo_GameResLogin.Size(m)
}
func (m *GameResLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResLogin.DiscardUnknown(m)
}

var xxx_messageInfo_GameResLogin proto.InternalMessageInfo

// 同步角色信息 1
type GameReqSyncActor struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameReqSyncActor) Reset()         { *m = GameReqSyncActor{} }
func (m *GameReqSyncActor) String() string { return proto.CompactTextString(m) }
func (*GameReqSyncActor) ProtoMessage()    {}
func (*GameReqSyncActor) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ecd7041722872b9, []int{6}
}

func (m *GameReqSyncActor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameReqSyncActor.Unmarshal(m, b)
}
func (m *GameReqSyncActor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameReqSyncActor.Marshal(b, m, deterministic)
}
func (m *GameReqSyncActor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameReqSyncActor.Merge(m, src)
}
func (m *GameReqSyncActor) XXX_Size() int {
	return xxx_messageInfo_GameReqSyncActor.Size(m)
}
func (m *GameReqSyncActor) XXX_DiscardUnknown() {
	xxx_messageInfo_GameReqSyncActor.DiscardUnknown(m)
}

var xxx_messageInfo_GameReqSyncActor proto.InternalMessageInfo

// 同步角色信息 2
type GameResSyncActor struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResSyncActor) Reset()         { *m = GameResSyncActor{} }
func (m *GameResSyncActor) String() string { return proto.CompactTextString(m) }
func (*GameResSyncActor) ProtoMessage()    {}
func (*GameResSyncActor) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ecd7041722872b9, []int{7}
}

func (m *GameResSyncActor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResSyncActor.Unmarshal(m, b)
}
func (m *GameResSyncActor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResSyncActor.Marshal(b, m, deterministic)
}
func (m *GameResSyncActor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResSyncActor.Merge(m, src)
}
func (m *GameResSyncActor) XXX_Size() int {
	return xxx_messageInfo_GameResSyncActor.Size(m)
}
func (m *GameResSyncActor) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResSyncActor.DiscardUnknown(m)
}

var xxx_messageInfo_GameResSyncActor proto.InternalMessageInfo

////////////////////////////////////////////////////////////////
// 推送登录信息(待定)
type GamePushLogin struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ActorName            string   `protobuf:"bytes,2,opt,name=actorName,proto3" json:"actorName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamePushLogin) Reset()         { *m = GamePushLogin{} }
func (m *GamePushLogin) String() string { return proto.CompactTextString(m) }
func (*GamePushLogin) ProtoMessage()    {}
func (*GamePushLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ecd7041722872b9, []int{8}
}

func (m *GamePushLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamePushLogin.Unmarshal(m, b)
}
func (m *GamePushLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamePushLogin.Marshal(b, m, deterministic)
}
func (m *GamePushLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamePushLogin.Merge(m, src)
}
func (m *GamePushLogin) XXX_Size() int {
	return xxx_messageInfo_GamePushLogin.Size(m)
}
func (m *GamePushLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_GamePushLogin.DiscardUnknown(m)
}

var xxx_messageInfo_GamePushLogin proto.InternalMessageInfo

func (m *GamePushLogin) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GamePushLogin) GetActorName() string {
	if m != nil {
		return m.ActorName
	}
	return ""
}

////////////////////////////////////////////////////////////////
// 广播登录信息(待定)
type GameBCLogin struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ActorName            string   `protobuf:"bytes,2,opt,name=actorName,proto3" json:"actorName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameBCLogin) Reset()         { *m = GameBCLogin{} }
func (m *GameBCLogin) String() string { return proto.CompactTextString(m) }
func (*GameBCLogin) ProtoMessage()    {}
func (*GameBCLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ecd7041722872b9, []int{9}
}

func (m *GameBCLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBCLogin.Unmarshal(m, b)
}
func (m *GameBCLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBCLogin.Marshal(b, m, deterministic)
}
func (m *GameBCLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBCLogin.Merge(m, src)
}
func (m *GameBCLogin) XXX_Size() int {
	return xxx_messageInfo_GameBCLogin.Size(m)
}
func (m *GameBCLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBCLogin.DiscardUnknown(m)
}

var xxx_messageInfo_GameBCLogin proto.InternalMessageInfo

func (m *GameBCLogin) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GameBCLogin) GetActorName() string {
	if m != nil {
		return m.ActorName
	}
	return ""
}

func init() {
	proto.RegisterType((*GameReqHeartBeat)(nil), "protos.GameReqHeartBeat")
	proto.RegisterType((*GameResHeartBeat)(nil), "protos.GameResHeartBeat")
	proto.RegisterType((*GameReqSyncTime)(nil), "protos.GameReqSyncTime")
	proto.RegisterType((*GameResSyncTime)(nil), "protos.GameResSyncTime")
	proto.RegisterType((*GameReqLogin)(nil), "protos.GameReqLogin")
	proto.RegisterType((*GameResLogin)(nil), "protos.GameResLogin")
	proto.RegisterType((*GameReqSyncActor)(nil), "protos.GameReqSyncActor")
	proto.RegisterType((*GameResSyncActor)(nil), "protos.GameResSyncActor")
	proto.RegisterType((*GamePushLogin)(nil), "protos.GamePushLogin")
	proto.RegisterType((*GameBCLogin)(nil), "protos.GameBCLogin")
}

func init() { proto.RegisterFile("gamemsg.proto", fileDescriptor_0ecd7041722872b9) }

var fileDescriptor_0ecd7041722872b9 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x9a, 0x54, 0xea, 0x41, 0xa1, 0x58, 0x08, 0x79, 0x60, 0xa8, 0x32, 0x75, 0x62,
	0x61, 0x46, 0x88, 0x32, 0xc0, 0x80, 0x10, 0x0a, 0xfc, 0x81, 0xa3, 0x3d, 0xa5, 0x1e, 0x2e, 0x86,
	0xd8, 0x19, 0xf2, 0xef, 0xd1, 0x5d, 0x5c, 0x99, 0x99, 0xc9, 0xef, 0x7d, 0xba, 0x3b, 0xbd, 0x27,
	0xc3, 0xb2, 0x45, 0x26, 0x0e, 0xed, 0xed, 0x77, 0xef, 0xa3, 0x37, 0x73, 0x7d, 0x42, 0x6d, 0x60,
	0xf5, 0x8c, 0x4c, 0x0d, 0xfd, 0xbc, 0x10, 0xf6, 0x71, 0x4b, 0x18, 0x33, 0x0b, 0x99, 0x5d, 0xc2,
	0x45, 0x9a, 0xfb, 0x18, 0xbb, 0xdd, 0xa7, 0x63, 0xaa, 0xc7, 0x23, 0x0a, 0x47, 0x64, 0x0c, 0x94,
	0x23, 0x61, 0x6f, 0x8b, 0x75, 0xb1, 0xa9, 0x1a, 0xd5, 0xe6, 0x0a, 0x2a, 0xf6, 0x5d, 0x3c, 0xd8,
	0x13, 0x85, 0x93, 0x31, 0x2b, 0x98, 0xed, 0x71, 0xb4, 0x33, 0x65, 0x22, 0xcd, 0x35, 0xcc, 0xd9,
	0x75, 0x43, 0x24, 0x5b, 0x2a, 0x4c, 0x4e, 0x6e, 0x46, 0xc7, 0x64, 0xab, 0x75, 0xb1, 0x29, 0x1b,
	0xd5, 0xf5, 0x39, 0x9c, 0xa5, 0x34, 0xaf, 0xbe, 0x75, 0x5d, 0xf6, 0x61, 0xf2, 0xb9, 0x95, 0x44,
	0x7b, 0xdc, 0x45, 0xdf, 0xff, 0x69, 0x95, 0xd9, 0x03, 0x2c, 0x85, 0xbd, 0x0f, 0xe1, 0xa0, 0x8b,
	0x12, 0x6b, 0x70, 0xfb, 0x94, 0x5f, 0xa4, 0xb9, 0x81, 0x05, 0xca, 0xec, 0x1b, 0x32, 0x69, 0x85,
	0x45, 0x93, 0x41, 0x7d, 0x0f, 0xa7, 0x72, 0x60, 0xfb, 0xf4, 0xaf, 0xf5, 0xaf, 0xe9, 0x17, 0xee,
	0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x85, 0xdf, 0x51, 0x8f, 0x9d, 0x01, 0x00, 0x00,
}
