// Code generated by protoc-gen-go. DO NOT EDIT.
// source: socialmsg.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

////////////////////////////////////////////////////////////////
// 心跳 1
type SocialReqHeartBeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialReqHeartBeat) Reset()         { *m = SocialReqHeartBeat{} }
func (m *SocialReqHeartBeat) String() string { return proto.CompactTextString(m) }
func (*SocialReqHeartBeat) ProtoMessage()    {}
func (*SocialReqHeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f02ce0266e008a, []int{0}
}

func (m *SocialReqHeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialReqHeartBeat.Unmarshal(m, b)
}
func (m *SocialReqHeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialReqHeartBeat.Marshal(b, m, deterministic)
}
func (m *SocialReqHeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialReqHeartBeat.Merge(m, src)
}
func (m *SocialReqHeartBeat) XXX_Size() int {
	return xxx_messageInfo_SocialReqHeartBeat.Size(m)
}
func (m *SocialReqHeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialReqHeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_SocialReqHeartBeat proto.InternalMessageInfo

// 心跳 2
type SocialResHeartBeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialResHeartBeat) Reset()         { *m = SocialResHeartBeat{} }
func (m *SocialResHeartBeat) String() string { return proto.CompactTextString(m) }
func (*SocialResHeartBeat) ProtoMessage()    {}
func (*SocialResHeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f02ce0266e008a, []int{1}
}

func (m *SocialResHeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialResHeartBeat.Unmarshal(m, b)
}
func (m *SocialResHeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialResHeartBeat.Marshal(b, m, deterministic)
}
func (m *SocialResHeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialResHeartBeat.Merge(m, src)
}
func (m *SocialResHeartBeat) XXX_Size() int {
	return xxx_messageInfo_SocialResHeartBeat.Size(m)
}
func (m *SocialResHeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialResHeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_SocialResHeartBeat proto.InternalMessageInfo

// 同步时间 1
type SocialReqSyncTime struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialReqSyncTime) Reset()         { *m = SocialReqSyncTime{} }
func (m *SocialReqSyncTime) String() string { return proto.CompactTextString(m) }
func (*SocialReqSyncTime) ProtoMessage()    {}
func (*SocialReqSyncTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f02ce0266e008a, []int{2}
}

func (m *SocialReqSyncTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialReqSyncTime.Unmarshal(m, b)
}
func (m *SocialReqSyncTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialReqSyncTime.Marshal(b, m, deterministic)
}
func (m *SocialReqSyncTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialReqSyncTime.Merge(m, src)
}
func (m *SocialReqSyncTime) XXX_Size() int {
	return xxx_messageInfo_SocialReqSyncTime.Size(m)
}
func (m *SocialReqSyncTime) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialReqSyncTime.DiscardUnknown(m)
}

var xxx_messageInfo_SocialReqSyncTime proto.InternalMessageInfo

// 同步时间 2
type SocialResSyncTime struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Minute               int32    `protobuf:"varint,4,opt,name=minute,proto3" json:"minute,omitempty"`
	Time                 uint64   `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialResSyncTime) Reset()         { *m = SocialResSyncTime{} }
func (m *SocialResSyncTime) String() string { return proto.CompactTextString(m) }
func (*SocialResSyncTime) ProtoMessage()    {}
func (*SocialResSyncTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f02ce0266e008a, []int{3}
}

func (m *SocialResSyncTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialResSyncTime.Unmarshal(m, b)
}
func (m *SocialResSyncTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialResSyncTime.Marshal(b, m, deterministic)
}
func (m *SocialResSyncTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialResSyncTime.Merge(m, src)
}
func (m *SocialResSyncTime) XXX_Size() int {
	return xxx_messageInfo_SocialResSyncTime.Size(m)
}
func (m *SocialResSyncTime) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialResSyncTime.DiscardUnknown(m)
}

var xxx_messageInfo_SocialResSyncTime proto.InternalMessageInfo

func (m *SocialResSyncTime) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *SocialResSyncTime) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *SocialResSyncTime) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *SocialResSyncTime) GetMinute() int32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *SocialResSyncTime) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// 登录验证 1
type SocialReqLogin struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialReqLogin) Reset()         { *m = SocialReqLogin{} }
func (m *SocialReqLogin) String() string { return proto.CompactTextString(m) }
func (*SocialReqLogin) ProtoMessage()    {}
func (*SocialReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f02ce0266e008a, []int{4}
}

func (m *SocialReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialReqLogin.Unmarshal(m, b)
}
func (m *SocialReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialReqLogin.Marshal(b, m, deterministic)
}
func (m *SocialReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialReqLogin.Merge(m, src)
}
func (m *SocialReqLogin) XXX_Size() int {
	return xxx_messageInfo_SocialReqLogin.Size(m)
}
func (m *SocialReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_SocialReqLogin proto.InternalMessageInfo

// 登录验证 2
type SocialResLogin struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialResLogin) Reset()         { *m = SocialResLogin{} }
func (m *SocialResLogin) String() string { return proto.CompactTextString(m) }
func (*SocialResLogin) ProtoMessage()    {}
func (*SocialResLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f02ce0266e008a, []int{5}
}

func (m *SocialResLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialResLogin.Unmarshal(m, b)
}
func (m *SocialResLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialResLogin.Marshal(b, m, deterministic)
}
func (m *SocialResLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialResLogin.Merge(m, src)
}
func (m *SocialResLogin) XXX_Size() int {
	return xxx_messageInfo_SocialResLogin.Size(m)
}
func (m *SocialResLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialResLogin.DiscardUnknown(m)
}

var xxx_messageInfo_SocialResLogin proto.InternalMessageInfo

// 同步角色信息 1
type SocialReqSyncActor struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialReqSyncActor) Reset()         { *m = SocialReqSyncActor{} }
func (m *SocialReqSyncActor) String() string { return proto.CompactTextString(m) }
func (*SocialReqSyncActor) ProtoMessage()    {}
func (*SocialReqSyncActor) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f02ce0266e008a, []int{6}
}

func (m *SocialReqSyncActor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialReqSyncActor.Unmarshal(m, b)
}
func (m *SocialReqSyncActor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialReqSyncActor.Marshal(b, m, deterministic)
}
func (m *SocialReqSyncActor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialReqSyncActor.Merge(m, src)
}
func (m *SocialReqSyncActor) XXX_Size() int {
	return xxx_messageInfo_SocialReqSyncActor.Size(m)
}
func (m *SocialReqSyncActor) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialReqSyncActor.DiscardUnknown(m)
}

var xxx_messageInfo_SocialReqSyncActor proto.InternalMessageInfo

// 同步角色信息 2
type SocialResSyncActor struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialResSyncActor) Reset()         { *m = SocialResSyncActor{} }
func (m *SocialResSyncActor) String() string { return proto.CompactTextString(m) }
func (*SocialResSyncActor) ProtoMessage()    {}
func (*SocialResSyncActor) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f02ce0266e008a, []int{7}
}

func (m *SocialResSyncActor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialResSyncActor.Unmarshal(m, b)
}
func (m *SocialResSyncActor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialResSyncActor.Marshal(b, m, deterministic)
}
func (m *SocialResSyncActor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialResSyncActor.Merge(m, src)
}
func (m *SocialResSyncActor) XXX_Size() int {
	return xxx_messageInfo_SocialResSyncActor.Size(m)
}
func (m *SocialResSyncActor) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialResSyncActor.DiscardUnknown(m)
}

var xxx_messageInfo_SocialResSyncActor proto.InternalMessageInfo

////////////////////////////////////////////////////////////////
// 推送登录信息
type SocialPushLogin struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ActorName            string   `protobuf:"bytes,2,opt,name=actorName,proto3" json:"actorName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialPushLogin) Reset()         { *m = SocialPushLogin{} }
func (m *SocialPushLogin) String() string { return proto.CompactTextString(m) }
func (*SocialPushLogin) ProtoMessage()    {}
func (*SocialPushLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f02ce0266e008a, []int{8}
}

func (m *SocialPushLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialPushLogin.Unmarshal(m, b)
}
func (m *SocialPushLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialPushLogin.Marshal(b, m, deterministic)
}
func (m *SocialPushLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialPushLogin.Merge(m, src)
}
func (m *SocialPushLogin) XXX_Size() int {
	return xxx_messageInfo_SocialPushLogin.Size(m)
}
func (m *SocialPushLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialPushLogin.DiscardUnknown(m)
}

var xxx_messageInfo_SocialPushLogin proto.InternalMessageInfo

func (m *SocialPushLogin) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SocialPushLogin) GetActorName() string {
	if m != nil {
		return m.ActorName
	}
	return ""
}

////////////////////////////////////////////////////////////////
// 广播登录信息
type SocialBCLogin struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ActorName            string   `protobuf:"bytes,2,opt,name=actorName,proto3" json:"actorName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialBCLogin) Reset()         { *m = SocialBCLogin{} }
func (m *SocialBCLogin) String() string { return proto.CompactTextString(m) }
func (*SocialBCLogin) ProtoMessage()    {}
func (*SocialBCLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_39f02ce0266e008a, []int{9}
}

func (m *SocialBCLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialBCLogin.Unmarshal(m, b)
}
func (m *SocialBCLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialBCLogin.Marshal(b, m, deterministic)
}
func (m *SocialBCLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialBCLogin.Merge(m, src)
}
func (m *SocialBCLogin) XXX_Size() int {
	return xxx_messageInfo_SocialBCLogin.Size(m)
}
func (m *SocialBCLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialBCLogin.DiscardUnknown(m)
}

var xxx_messageInfo_SocialBCLogin proto.InternalMessageInfo

func (m *SocialBCLogin) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SocialBCLogin) GetActorName() string {
	if m != nil {
		return m.ActorName
	}
	return ""
}

func init() {
	proto.RegisterType((*SocialReqHeartBeat)(nil), "protos.SocialReqHeartBeat")
	proto.RegisterType((*SocialResHeartBeat)(nil), "protos.SocialResHeartBeat")
	proto.RegisterType((*SocialReqSyncTime)(nil), "protos.SocialReqSyncTime")
	proto.RegisterType((*SocialResSyncTime)(nil), "protos.SocialResSyncTime")
	proto.RegisterType((*SocialReqLogin)(nil), "protos.SocialReqLogin")
	proto.RegisterType((*SocialResLogin)(nil), "protos.SocialResLogin")
	proto.RegisterType((*SocialReqSyncActor)(nil), "protos.SocialReqSyncActor")
	proto.RegisterType((*SocialResSyncActor)(nil), "protos.SocialResSyncActor")
	proto.RegisterType((*SocialPushLogin)(nil), "protos.SocialPushLogin")
	proto.RegisterType((*SocialBCLogin)(nil), "protos.SocialBCLogin")
}

func init() { proto.RegisterFile("socialmsg.proto", fileDescriptor_39f02ce0266e008a) }

var fileDescriptor_39f02ce0266e008a = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x9a, 0x54, 0xea, 0x49, 0xd0, 0x72, 0x54, 0xc8, 0x03, 0x43, 0x95, 0xa9, 0x13,
	0x0b, 0x3f, 0x00, 0xb5, 0x2c, 0x0c, 0x08, 0xa1, 0x94, 0x3f, 0x60, 0xd2, 0x53, 0x6b, 0x09, 0xdb,
	0x60, 0x3b, 0x43, 0xc4, 0x9f, 0x47, 0x3e, 0x97, 0x38, 0xac, 0x9d, 0xfc, 0xee, 0xf3, 0xf9, 0xe9,
	0x3d, 0x19, 0xe6, 0xde, 0xb6, 0x4a, 0x7e, 0x6a, 0x7f, 0xb8, 0xff, 0x72, 0x36, 0x58, 0x9c, 0xf2,
	0xe1, 0xeb, 0x25, 0xe0, 0x8e, 0xaf, 0x1a, 0xfa, 0x7e, 0x26, 0xe9, 0xc2, 0x96, 0x64, 0x18, 0x53,
	0x9f, 0xe9, 0x0d, 0x5c, 0x0f, 0xbb, 0xbb, 0xde, 0xb4, 0xef, 0x4a, 0x53, 0xfd, 0x93, 0xa1, 0xff,
	0x83, 0x88, 0x50, 0xf6, 0x24, 0x9d, 0x28, 0x56, 0xc5, 0xba, 0x6a, 0x58, 0xe3, 0x12, 0x2a, 0x6d,
	0x4d, 0x38, 0x8a, 0x0b, 0x86, 0x69, 0xc0, 0x05, 0x4c, 0xf6, 0xb2, 0x17, 0x13, 0x66, 0x51, 0xe2,
	0x2d, 0x4c, 0xb5, 0x32, 0x5d, 0x20, 0x51, 0x32, 0x3c, 0x4d, 0xd1, 0x33, 0x28, 0x4d, 0xa2, 0x5a,
	0x15, 0xeb, 0xb2, 0x61, 0x5d, 0x2f, 0xe0, 0x6a, 0x48, 0xf4, 0x62, 0x0f, 0xca, 0x8c, 0x89, 0x4f,
	0x64, 0xdc, 0x30, 0x06, 0xdc, 0xb4, 0xc1, 0xba, 0x7f, 0x0d, 0x33, 0xdd, 0xc0, 0x3c, 0xd1, 0xb7,
	0xce, 0x1f, 0xf9, 0x79, 0x0c, 0xd8, 0xa9, 0xfd, 0xa9, 0x49, 0x94, 0x78, 0x07, 0x33, 0x19, 0xb7,
	0x5f, 0xa5, 0x26, 0x2e, 0x33, 0x6b, 0x32, 0xa8, 0x1f, 0xe1, 0x32, 0x59, 0x6c, 0x9f, 0xce, 0x32,
	0xf8, 0x48, 0x3f, 0xf3, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x44, 0xa7, 0x47, 0xfd, 0xb3, 0x01,
	0x00, 0x00,
}
